---
- hosts: db_nodes
  become: yes
  vars:
    DB_NAME: "blog"
    DB_USER: "bloger"
    DB_PW: "bloger!"
  tasks:
    - name: "provide custom repo for mariadb"
      copy:
        src: "files/MariaDB.repo"
        dest: "/etc/yum.repos.d/MariaDB.repo"
    - name: "install mariadb dependencies"
      yum:
        name: "{{ MARIADB_PACKAGES }}" 
        state: present
      vars:
        MARIADB_PACKAGES: 
          - MariaDB-server
          - MariaDB-client   
    - name: "start mysql server"
      service:
        name: mariadb
        state: started
    - name: "install db manage dependencies"
      yum:
        name: python2-PyMySQL
        state: present
    - name: "create db"
      mysql_db:
        login_unix_socket: '/var/lib/mysql/mysql.sock'
        name: "{{ DB_NAME }}"
        state: present
    - name: "create db user"
      mysql_user:
        login_unix_socket: '/var/lib/mysql/mysql.sock'
        name: "{{ DB_USER }}"
        password: "{{ DB_PW }}"
        priv: "{{ DB_NAME ~'.*:ALL,GRANT'}}"
        state: present
- hosts: wp_nodes
  become: yes
  vars:
    my_fav_packages:
      - cowsay
      - mc
      - git
    WP_DOWNLOAD_URL: https://wordpress.org/latest.zip
    WP_DEST_DIR: /var/www/blog
    EPEL_RPM_URL: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    PHP_REPO_URL: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
  tasks:
    - name: "Create hello world"
      file:
        path: ~/hello_world.txt
        mode: '0600'
        state: touch
    - name: "Install my favorite packages"
      yum:
        name: "{{ my_fav_packages }}"
        state: latest
    - name: "Download wordpress"
      get_url:
        url: "{{ WP_DOWNLOAD_URL }}"  
        dest: /tmp/wordpress.zip
    - name: "Ensure blog dest dir exist"
      file: 
        path: "{{WP_DEST_DIR}}"   
        state: directory 
    - name: "Unarchive WP"
      unarchive:
        src: /tmp/wordpress.zip
        dest: "{{WP_DEST_DIR}}"
        remote_src: yes   
    - name: "install epel repo"
      yum:
        name: "{{ EPEL_RPM_URL }}"
        state: present
    - name: "install php repo"
      yum: 
        name: "{{ PHP_REPO_URL }}"
        state: present
    - name: "install php dependiencies"
      yum:
        name:
          - "php74"
          - "php74-php"
          - "php74-php-mysqlnd"
          - "php74-php-pecl-mysql"
        state: present
    - name: "install HTTP server"
      yum:
        name: httpd
        state: present
    - name: "copy httod vhost"
      template: 
        src: "files/blog-vhost.conf"
        dest: "/etc/httpd/conf.d/blog.conf"
    - name: "copy wp-config into place"
      template:
        src: "files/wp-config-sample.php"
        dest: "{{ WP_DEST_DIR }}/wordpress/wp-config.php"
    - file:
        path: /etc/httpd/conf.d/welcome.conf
        state: absent
    - name: "restart httpd"
      service:
        name: httpd
        state: restarted
